# Generated by `fastlane dist`. Edit the lane, not this file.
cask "spooktacular" do
  version "0.2.0"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  url "https://github.com/Spooky-Labs/spooktacular/releases/download/v#{version}/Spooktacular-#{version}-macos-arm64.zip"
  name "Spooktacular"
  desc "Create macOS virtual machines in seconds from a shared base image"
  homepage "https://spooktacular.app/"

  # A bare symbol is already a minimum ("this release or newer"), which
  # is what brew style enforces. The real floor is macOS 27, but
  # Homebrew rejects numeric versions here and there is no verified
  # symbol for 27 yet, so this sits one release low on purpose: an
  # unknown symbol would break the cask outright, whereas this only lets
  # a macOS 26 user install and read the caveat. Tighten it when the
  # symbol lands.
  depends_on macos: :tahoe
  depends_on arch: :arm64

  app "Spooktacular.app"
  binary "#{appdir}/Spooktacular.app/Contents/MacOS/spook"

  zap trash: [
    "~/Library/Application Support/com.spooktacular.app",
    "~/Library/Caches/com.spooktacular.app",
    "~/Library/Preferences/com.spooktacular.app.plist",
    "~/Library/Saved Application State/com.spooktacular.app.savedState",
  ]

  caveats <<~EOS
    Creating macOS virtual machines requires macOS 27 or later, because
    the shared base image and its copy-on-write overlays are built on
    DiskImageKit. On macOS 26 the app installs and runs, and Linux guests
    work, but macOS guests will refuse to be created.

    Spooktacular keeps virtual machines and cached base images in
    ~/.spooktacular. Deleting the app does not remove them; `brew uninstall
    --zap` does not either, because losing a VM to an uninstall would be
    worse than leaving the directory behind.

    The first macOS VM you create installs macOS into a shared base image.
    That takes 10-20 minutes and asks for an administrator password once.
    Every VM created afterwards takes seconds and needs no privileges.
  EOS
end
