import Foundation

/// Generates user-data scripts for remote desktop (Screen Sharing) VMs.
///
/// When `spook create` is invoked with `--remote-desktop`, this
/// template generates a shell script that:
///
/// 1. Enables Screen Sharing (VNC) via Apple Remote Desktop's
///    `kickstart` tool
/// 2. Enables Remote Login (SSH) via `systemsetup`
///
/// The generated script is written to a temporary file and used
/// as the VM's user-data script, following the same provisioning
/// pipeline as any other user-data.
///
/// ## Usage
///
/// ```swift
/// let url = try RemoteDesktopTemplate.generate()
/// // Use `url` as the --user-data script for the VM.
/// ```
///
/// ## Security
///
/// The script enables full VNC access with all privileges. In
/// production environments, restrict access using the `-access`
/// flags of the `kickstart` tool and configure a VNC password.
public enum RemoteDesktopTemplate {

    /// Generates a remote desktop setup script.
    ///
    /// Creates a temporary shell script that enables Screen Sharing
    /// (VNC) and Remote Login (SSH) on the VM.
    ///
    /// - Returns: A file URL pointing to the generated script in
    ///   a temporary directory.
    /// - Throws: An error if the script cannot be written to disk.
    public static func generate() throws -> URL {
        let url = try ScriptFile.writeToTempDirectory(
            script: scriptContent(), fileName: "remote-desktop-setup.sh"
        )
        return url
    }

    /// Generates the shell script content for remote desktop setup.
    ///
    /// Extracted as a separate method for testability.
    ///
    /// - Returns: The complete shell script as a string.
    public static func scriptContent() -> String {
        """
        #!/bin/bash
        set -euo pipefail

        # Remote Desktop Setup
        # Generated by Spooktacular

        # Enable Screen Sharing (VNC) via Apple Remote Desktop.
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \\
            -activate -configure -access -on -restart -agent -privs -all

        # Enable Remote Login (SSH).
        sudo launchctl bootstrap system /System/Library/LaunchDaemons/ssh.plist 2>/dev/null || true

        echo "Screen Sharing enabled. Connect via VNC."
        """
    }

}
