import Foundation
import os

/// Generates user-data scripts for GitHub Actions runner VMs.
///
/// When `spook create` is invoked with `--github-runner`, this
/// template generates a shell script that:
///
/// 1. Downloads the latest GitHub Actions runner for macOS ARM64
/// 2. Configures it with the specified repository and token
/// 3. Starts the runner in unattended mode
///
/// The generated script is written to a temporary file and used
/// as the VM's user-data script, following the same provisioning
/// pipeline as any other user-data.
///
/// ## Usage
///
/// ```swift
/// let url = try GitHubRunnerTemplate.generate(
///     repo: "myorg/myrepo",
///     token: "AABCDEF..."
/// )
/// // Use `url` as the --user-data script for the VM.
/// ```
///
/// ## Security
///
/// The registration token is embedded in the script file. The
/// script is written to a temporary directory with restricted
/// permissions. Tokens are short-lived (1 hour) per GitHub's
/// design, limiting the exposure window.
public enum GitHubRunnerTemplate {

    /// Generates a GitHub Actions runner setup script.
    ///
    /// Creates a temporary shell script that downloads, configures,
    /// and starts a GitHub Actions self-hosted runner.
    ///
    /// - Parameters:
    ///   - repo: The GitHub repository in `owner/repo` format
    ///     (e.g., `"myorg/myrepo"`).
    ///   - token: The runner registration token obtained from
    ///     GitHub's API or the repository settings page.
    ///   - labels: Additional labels for the runner. The runner
    ///     always includes the `self-hosted`, `macOS`, and `ARM64`
    ///     labels. Defaults to an empty array.
    ///   - ephemeral: If `true`, the runner exits after completing
    ///     one job. Defaults to `false`.
    /// - Returns: A file URL pointing to the generated script in
    ///   a temporary directory.
    /// - Throws: An error if the script cannot be written to disk.
    public static func generate(
        repo: String,
        token: String,
        labels: [String] = [],
        ephemeral: Bool = false
    ) throws -> URL {
        let script = scriptContent(repo: repo, token: token, labels: labels, ephemeral: ephemeral)
        let url = try writeToTempFile(script)
        Log.provision.info("Generated GitHub runner script for \(repo, privacy: .public)")
        return url
    }

    /// Generates the shell script content for a GitHub Actions runner.
    ///
    /// Extracted as a separate method for testability.
    ///
    /// - Parameters:
    ///   - repo: The GitHub repository in `owner/repo` format.
    ///   - token: The runner registration token.
    ///   - labels: Additional runner labels.
    ///   - ephemeral: Whether the runner exits after one job.
    /// - Returns: The complete shell script as a string.
    public static func scriptContent(
        repo: String,
        token: String,
        labels: [String] = [],
        ephemeral: Bool = false
    ) -> String {
        var configFlags = [
            "--url \"https://github.com/\(repo)\"",
            "--token \"\(token)\"",
            "--unattended",
            "--replace",
        ]

        if !labels.isEmpty {
            configFlags.append("--labels \"\(labels.joined(separator: ","))\"")
        }

        if ephemeral {
            configFlags.append("--ephemeral")
        }

        let configLine = configFlags.joined(separator: " ")

        return """
        #!/bin/bash
        set -euo pipefail

        # GitHub Actions Runner Setup
        # Generated by Spooktacular

        cd /Users/admin
        mkdir -p actions-runner && cd actions-runner

        # Download the latest runner for macOS ARM64.
        LATEST=$(curl -s https://api.github.com/repos/actions/runner/releases/latest \\
            | grep -o 'https.*osx-arm64.*tar.gz' \\
            | head -1)

        if [ -z "$LATEST" ]; then
            echo "Error: Could not determine latest runner URL." >&2
            exit 1
        fi

        echo "Downloading runner from $LATEST..."
        curl -sL "$LATEST" | tar xz

        # Configure the runner.
        echo "Configuring runner for \(repo)..."
        ./config.sh \(configLine)

        # Start the runner.
        echo "Starting runner..."
        ./run.sh
        """
    }

    /// Writes a script string to a temporary file.
    ///
    /// - Parameter script: The script content to write.
    /// - Returns: The file URL of the written script.
    /// - Throws: An error if the file cannot be created.
    static func writeToTempFile(_ script: String) throws -> URL {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("spooktacular-\(UUID().uuidString)")
        try FileManager.default.createDirectory(
            at: tempDir,
            withIntermediateDirectories: true
        )

        let scriptURL = tempDir.appendingPathComponent("github-runner-setup.sh")
        try Data(script.utf8).write(to: scriptURL, options: .atomic)

        // Make executable.
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: scriptURL.path
        )

        return scriptURL
    }
}
