import Foundation
import os

/// Generates user-data scripts for OpenClaw AI agent VMs.
///
/// When `spook create` is invoked with `--openclaw`, this
/// template generates a shell script that:
///
/// 1. Installs Homebrew (if not already present)
/// 2. Installs Node.js 24 via Homebrew
/// 3. Installs OpenClaw globally via npm
/// 4. Runs `openclaw onboard --install-daemon` to configure and
///    start the gateway daemon
///
/// The generated script is written to a temporary file and used
/// as the VM's user-data script, following the same provisioning
/// pipeline as any other user-data.
///
/// ## Usage
///
/// ```swift
/// let url = try OpenClawTemplate.generate()
/// // Use `url` as the --user-data script for the VM.
/// ```
///
/// ## Security
///
/// API keys should be passed via a shared folder (`--share`),
/// not embedded in the script. The gateway daemon listens on
/// port 18789 by default.
public enum OpenClawTemplate {

    /// Generates an OpenClaw setup script.
    ///
    /// Creates a temporary shell script that installs Homebrew,
    /// Node.js 24, OpenClaw, and starts the gateway daemon.
    ///
    /// - Returns: A file URL pointing to the generated script in
    ///   a temporary directory.
    /// - Throws: An error if the script cannot be written to disk.
    public static func generate() throws -> URL {
        let script = scriptContent()
        let url = try writeToTempFile(script)
        Log.provision.info("Generated OpenClaw script")
        return url
    }

    /// Generates the shell script content for OpenClaw setup.
    ///
    /// Extracted as a separate method for testability.
    ///
    /// - Returns: The complete shell script as a string.
    public static func scriptContent() -> String {
        """
        #!/bin/bash
        set -euo pipefail

        # OpenClaw AI Agent Setup
        # Generated by Spooktacular

        # Install Homebrew.
        if ! command -v brew &>/dev/null; then
            NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            eval "$(/opt/homebrew/bin/brew shellenv)"
            echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshrc
        fi

        # Install Node.js 24.
        brew install node@24
        export PATH="/opt/homebrew/opt/node@24/bin:$PATH"
        echo 'export PATH="/opt/homebrew/opt/node@24/bin:$PATH"' >> ~/.zshrc

        # Install OpenClaw.
        npm install -g openclaw@latest

        # Install and start gateway daemon.
        openclaw onboard --install-daemon

        echo "OpenClaw installed and running on port 18789"
        """
    }

    /// Writes a script string to a temporary file.
    ///
    /// - Parameter script: The script content to write.
    /// - Returns: The file URL of the written script.
    /// - Throws: An error if the file cannot be created.
    static func writeToTempFile(_ script: String) throws -> URL {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("spooktacular-\(UUID().uuidString)")
        try FileManager.default.createDirectory(
            at: tempDir,
            withIntermediateDirectories: true
        )

        let scriptURL = tempDir.appendingPathComponent("openclaw-setup.sh")
        try Data(script.utf8).write(to: scriptURL, options: .atomic)

        // Make executable.
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: scriptURL.path
        )

        return scriptURL
    }
}
