import Foundation
import os

/// Generates user-data scripts for remote desktop (Screen Sharing) VMs.
///
/// When `spook create` is invoked with `--remote-desktop`, this
/// template generates a shell script that:
///
/// 1. Enables Screen Sharing (VNC) via Apple Remote Desktop's
///    `kickstart` tool
/// 2. Enables Remote Login (SSH) via `systemsetup`
///
/// The generated script is written to a temporary file and used
/// as the VM's user-data script, following the same provisioning
/// pipeline as any other user-data.
///
/// ## Usage
///
/// ```swift
/// let url = try RemoteDesktopTemplate.generate()
/// // Use `url` as the --user-data script for the VM.
/// ```
///
/// ## Security
///
/// The script enables full VNC access with all privileges. In
/// production environments, restrict access using the `-access`
/// flags of the `kickstart` tool and configure a VNC password.
public enum RemoteDesktopTemplate {

    /// Generates a remote desktop setup script.
    ///
    /// Creates a temporary shell script that enables Screen Sharing
    /// (VNC) and Remote Login (SSH) on the VM.
    ///
    /// - Returns: A file URL pointing to the generated script in
    ///   a temporary directory.
    /// - Throws: An error if the script cannot be written to disk.
    public static func generate() throws -> URL {
        let script = scriptContent()
        let url = try writeToTempFile(script)
        Log.provision.info("Generated remote desktop script")
        return url
    }

    /// Generates the shell script content for remote desktop setup.
    ///
    /// Extracted as a separate method for testability.
    ///
    /// - Returns: The complete shell script as a string.
    public static func scriptContent() -> String {
        """
        #!/bin/bash
        set -euo pipefail

        # Remote Desktop Setup
        # Generated by Spooktacular

        # Enable Screen Sharing (VNC) via Apple Remote Desktop.
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \\
            -activate -configure -access -on -restart -agent -privs -all

        # Enable Remote Login (SSH).
        sudo systemsetup -setremotelogin on

        echo "Screen Sharing enabled. Connect via VNC."
        """
    }

    /// Writes a script string to a temporary file.
    ///
    /// - Parameter script: The script content to write.
    /// - Returns: The file URL of the written script.
    /// - Throws: An error if the file cannot be created.
    static func writeToTempFile(_ script: String) throws -> URL {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("spooktacular-\(UUID().uuidString)")
        try FileManager.default.createDirectory(
            at: tempDir,
            withIntermediateDirectories: true
        )

        let scriptURL = tempDir.appendingPathComponent("remote-desktop-setup.sh")
        try Data(script.utf8).write(to: scriptURL, options: .atomic)

        // Make executable.
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: scriptURL.path
        )

        return scriptURL
    }
}
