import Foundation

/// Produces the bash script that, when run as root inside a
/// freshly-booted VM, installs the supplied
/// ``MDMEnrollmentProfile`` and triggers `mdmclient`
/// enrollment with the host's embedded MDM server.
///
/// ## How this fits the existing bootstrap chain
///
/// We already have a working out-of-the-box flow:
///
/// 1. User runs the bundled `Spooktacular Provisioner.pkg` once
///    (from inside Guest Tools) — that drops a LaunchDaemon
///    `/Library/LaunchDaemons/com.spookylabs.spooktacular.provisioner.plist`
///    + a runner `/usr/local/libexec/spook-provision-runner.sh`.
/// 2. The daemon fires at every boot, mounts the virtio-fs
///    share at `/Library/Application Support/Spooktacular/provision/`,
///    and runs `first-boot.sh` if present.
/// 3. The host writes `first-boot.sh` into the bundle's
///    `provision/` directory via ``DiskInjector/inject(script:into:)``.
///
/// MDM enrollment layers on top of this without architectural
/// change: ``script(for:)`` produces the bash bytes that get
/// written as `first-boot.sh`. When the daemon picks the
/// script up and runs it as root, it:
///
/// - Drops the enrollment `.mobileconfig` to a stable path
///   inside the guest filesystem,
/// - Runs `profiles install -path … -type system` (which
///   succeeds without signing because the script runs as root),
/// - Triggers `mdmclient` to dial the host's embedded MDM
///   server, completing enrollment.
///
/// After that first run, the host pushes commands directly via
/// ``MDMUserDataDispatcher`` and bypasses `first-boot.sh`
/// altogether — MDM is the steady-state delivery channel.
///
/// ## Why a bash heredoc, not a base64 blob
///
/// The profile is a small XML plist (a few KB). Embedding it
/// verbatim in a quoted heredoc keeps the script
/// human-readable for operators inspecting `first-boot.sh`
/// during incident response. Base64 would obscure it. The
/// quoted heredoc (`<<'EOF'`) prevents bash interpolation of
/// any `$` or backtick that might appear in the XML — which
/// in practice it doesn't, but defensively avoids a class of
/// "the profile contains a quoted variable name and bash
/// expanded it" failures.
public struct MDMEnrollmentBootstrap: Sendable {

    /// Stable on-disk path inside the guest where the
    /// `.mobileconfig` lands. Operators can `profiles list -O
    /// stdout` after first-boot and cross-reference this path
    /// to confirm the profile installed cleanly.
    public static let installedProfilePath = "/var/db/spooktacular/enrollment.mobileconfig"

    /// The enrollment profile to bootstrap. Owned by the
    /// caller; the bootstrap renders it once into the
    /// generated script and never reads it again.
    public let profile: MDMEnrollmentProfile

    public init(profile: MDMEnrollmentProfile) {
        self.profile = profile
    }

    // MARK: - Public API

    /// Generates the bash script bytes ready to hand to
    /// ``DiskInjector/inject(script:into:)``. Call once per
    /// VM-create.
    public func script() throws -> Data {
        let mobileconfig = try profile.mobileconfig()
        guard let xml = String(data: mobileconfig, encoding: .utf8) else {
            throw MDMEnrollmentBootstrapError.profileNotUTF8
        }
        // Sanity: a quoted heredoc is broken by a literal
        // `EOF_PROFILE` line inside the body. The profile is
        // generator-controlled XML and never contains a line
        // that's just our terminator, but we check fail-fast
        // so a future change to the profile can't silently
        // produce a malformed script.
        let terminator = "MDM_ENROLLMENT_PROFILE_EOF"
        if xml.range(of: "\n\(terminator)\n") != nil {
            throw MDMEnrollmentBootstrapError.profileContainsHeredocTerminator
        }

        let body = """
        #!/bin/bash
        # Spooktacular MDM enrollment bootstrap.
        #
        # Generated by MDMEnrollmentBootstrap. Runs once at the
        # next VM boot via the spook-provision-runner LaunchDaemon
        # (installed by Spooktacular Provisioner.pkg).
        #
        # 1. Drops the embedded `.mobileconfig` to a stable
        #    path on the guest filesystem.
        # 2. Calls `profiles install` — which, running as root,
        #    accepts the unsigned profile and starts the
        #    mdmclient enrollment dance.
        #
        # After this script completes, mdmclient has dialed
        # the host's embedded MDM server, the device's
        # Authenticate + TokenUpdate landed in the host's
        # MDMDeviceStore, and subsequent commands flow via
        # MDMUserDataDispatcher → /mdm/server poll loop.

        set -euo pipefail

        PROFILE_DIR="$(dirname "\(Self.installedProfilePath)")"
        PROFILE_PATH="\(Self.installedProfilePath)"

        /usr/bin/install -d -m 0700 -o root -g wheel "${PROFILE_DIR}"

        /bin/cat > "${PROFILE_PATH}" <<'\(terminator)'
        \(xml)
        \(terminator)

        /bin/chmod 0600 "${PROFILE_PATH}"
        /usr/sbin/chown root:wheel "${PROFILE_PATH}"

        # `profiles install -type system` needs the profile to
        # be signed UNLESS we're already root — which we are
        # via the LaunchDaemon root context. mdmclient picks
        # up the enrollment payload and contacts ServerURL.
        /usr/bin/profiles install -path "${PROFILE_PATH}" -type system

        echo "Spooktacular MDM enrollment profile installed: ${PROFILE_PATH}"
        """

        // Ensure the script ends with a newline — pkg's
        // postinstall + LaunchDaemon program execution expect
        // it; some shells choke on trailing-newline-less
        // scripts.
        let finalScript = body.hasSuffix("\n") ? body : body + "\n"
        guard let data = finalScript.data(using: .utf8) else {
            throw MDMEnrollmentBootstrapError.scriptNotEncodable
        }
        return data
    }
}

/// Errors thrown by ``MDMEnrollmentBootstrap``.
public enum MDMEnrollmentBootstrapError: Error, Sendable, Equatable {
    /// The supplied profile rendered to non-UTF-8 bytes.
    /// Should be impossible for an XML plist, but we surface
    /// the case rather than silently truncating.
    case profileNotUTF8

    /// Defensive: the profile XML contains a literal line
    /// matching our heredoc terminator, which would prematurely
    /// close the heredoc and corrupt the script. Theoretically
    /// impossible for a well-formed `MDMEnrollmentProfile`
    /// output, but the check fails fast if a future change
    /// breaks that invariant.
    case profileContainsHeredocTerminator

    /// The fully-formed script wasn't UTF-8-encodable. Should
    /// be impossible since we constructed it from String
    /// literals + UTF-8 plist data, but surfaced for clarity.
    case scriptNotEncodable
}
