import Foundation
import SpooktacularCore

/// Generates user-data scripts for GitHub Actions runner VMs.
///
/// When `spook create` is invoked with `--github-runner`, this
/// template generates a shell script that:
///
/// 1. Downloads the latest GitHub Actions runner for macOS ARM64
/// 2. Configures it with the specified repository and token
/// 3. Starts the runner in unattended mode
///
/// The generated script is written to a temporary file and used
/// as the VM's user-data script, following the same provisioning
/// pipeline as any other user-data.
///
/// ## Usage
///
/// ```swift
/// let url = try GitHubRunnerTemplate.generate(
///     repo: "myorg/myrepo",
///     token: "AABCDEF..."
/// )
/// // Use `url` as the --user-data script for the VM.
/// ```
///
/// ## Security
///
/// The registration token is embedded in the script file. The
/// script is written to a temporary directory with restricted
/// permissions. Tokens are short-lived (1 hour) per GitHub's
/// design, limiting the exposure window.
public enum GitHubRunnerTemplate {

    /// Generates a GitHub Actions runner setup script.
    ///
    /// Creates a temporary shell script that downloads, configures,
    /// and starts a GitHub Actions self-hosted runner.
    ///
    /// - Parameters:
    ///   - repo: The GitHub repository in `owner/repo` format
    ///     (e.g., `"myorg/myrepo"`).
    ///   - token: The runner registration token obtained from
    ///     GitHub's API or the repository settings page.
    ///   - labels: Additional labels for the runner. The runner
    ///     always includes the `self-hosted`, `macOS`, and `ARM64`
    ///     labels. Defaults to an empty array.
    ///   - ephemeral: If `true`, the runner exits after completing
    ///     one job. Defaults to `false`.
    /// - Returns: A file URL pointing to the generated script in
    ///   a temporary directory.
    /// - Throws: An error if the script cannot be written to disk.
    public static func generate(
        repo: String,
        token: String,
        labels: [String] = [],
        ephemeral: Bool = false
    ) throws -> URL {
        let url = try ScriptFile.writeToCache(
            script: scriptContent(repo: repo, token: token, labels: labels, ephemeral: ephemeral),
            fileName: "github-runner-setup.sh"
        )
        return url
    }

    /// Generates the shell script content for a GitHub Actions runner.
    ///
    /// Extracted as a separate method for testability.
    ///
    /// Each label is individually POSIX-shell-escaped before being
    /// joined on a comma and wrapped as a single quoted argument.
    /// A previous implementation joined first then escaped the whole
    /// string, which let a single-quote inside one label break out
    /// of the surrounding quoting — a classic metacharacter bug.
    ///
    /// - Parameters:
    ///   - repo: The GitHub repository in `owner/repo` format.
    ///   - token: The runner registration token.
    ///   - labels: Additional runner labels.
    ///   - ephemeral: Whether the runner exits after one job.
    /// - Returns: The complete shell script as a string.
    public static func scriptContent(
        repo: String,
        token: String,
        labels: [String] = [],
        ephemeral: Bool = false
    ) -> String {
        // Shell-safe quoting: wrap in single quotes and escape embedded single quotes.
        let safeRepo = repo.replacingOccurrences(of: "'", with: "'\\''")
        let safeToken = token.replacingOccurrences(of: "'", with: "'\\''")

        var configFlags = [
            "--url \"https://github.com/$REPO\"",
            "--token \"$TOKEN\"",
            "--unattended",
            "--replace",
        ]

        if !labels.isEmpty {
            // Escape each label *individually* first, then join on a
            // comma, then wrap the whole thing in outer single quotes.
            // `foo'bar` must become `foo'\''bar`; joining raw labels
            // and escaping only once lets `foo'bar,baz` slip through
            // as two quoted segments, breaking the argument.
            let escapedLabels = labels
                .map { $0.replacingOccurrences(of: "'", with: "'\\''") }
                .joined(separator: ",")
            configFlags.append("--labels '\(escapedLabels)'")
        }

        if ephemeral {
            configFlags.append("--ephemeral")
        }

        let configLine = configFlags.joined(separator: " ")

        return """
        #!/bin/bash
        set -euo pipefail

        # GitHub Actions Runner Setup
        # Generated by Spooktacular

        REPO='\(safeRepo)'
        TOKEN='\(safeToken)'

        cd /Users/admin
        mkdir -p actions-runner && cd actions-runner

        # Download the latest runner for macOS ARM64.
        LATEST=$(curl -s https://api.github.com/repos/actions/runner/releases/latest \\
            | python3 -c "import sys,json; assets=json.load(sys.stdin)['assets']; print(next(a['browser_download_url'] for a in assets if 'osx-arm64' in a['name'] and a['name'].endswith('.tar.gz')))" 2>/dev/null)

        if [ -z "$LATEST" ]; then
            echo "Error: Could not determine latest runner URL." >&2
            exit 1
        fi

        echo "Downloading runner from $LATEST..."
        curl -sL "$LATEST" | tar xz

        # Configure the runner.
        echo "Configuring runner for $REPO..."
        ./config.sh \(configLine)

        # Start the runner.
        echo "Starting runner..."
        ./run.sh
        """
    }

}
