import Foundation
import SpooktacularCore

/// Generates the guest-side shell script for activating
/// Rosetta 2 inside a Linux VM that was created with
/// ``VirtualMachineSpecification/rosettaEnabled`` set to
/// `true`.
///
/// Apple's Virtualization framework guidance for Rosetta is
/// explicit: *"The remaining steps required to activate
/// Rosetta in a Linux guest aren't commands that your app
/// can execute or that you can script from inside your
/// application to a Linux VM; the user must perform them
/// either interactively or as part of a script while logged
/// in to the Linux guest. You must communicate these
/// requirements to the user of your app."*
///
/// We honour that guidance by emitting a self-contained
/// shell script that the user runs once inside the guest
/// (via SSH, copy-paste into a terminal, or the existing
/// user-data provisioning pipeline).  The script is
/// idempotent: running it twice is a no-op.
///
/// Steps encoded in the script — all from Apple's
/// "Running Intel Binaries in Linux VMs with Rosetta"
/// documentation:
///
/// 1. Install the `binfmt-support` package (provides
///    `update-binfmts`).  Package manager is auto-detected
///    from `apt`, `dnf`, `yum`, or `pacman`.
/// 2. Create `/mnt/rosetta` as a mount point.
/// 3. Mount the virtio-fs tag `rosetta` at that path with
///    a persistent `/etc/fstab` entry so the mount survives
///    reboots.
/// 4. Register the Rosetta runtime binary with the kernel's
///    binfmt_misc subsystem using the exact `--magic` /
///    `--mask` / `--credentials yes --preserve yes
///    --fix-binary yes` arguments from Apple's docs.
///
/// The `magic` value matches the first 20 bytes of an
/// `x86_64` ELF header: `\x7fELF` magic, 64-bit class,
/// little-endian, ELF version 1, System V ABI (zeroed
/// padding), ET_EXEC/ET_DYN (`\x02\x00`), EM_X86_64
/// (`\x3e\x00`).  The `mask` ignores OS/ABI variation in
/// bytes 6–7 so glibc / musl / statically-linked binaries
/// all match.
///
/// Reference:
/// - [Mount the Shared Directory and Register Rosetta](https://developer.apple.com/documentation/virtualization/running-intel-binaries-in-linux-vms-with-rosetta#Mount-the-Shared-Directory-and-Register-Rosetta)
public enum LinuxRosettaTemplate {

    /// The virtio-fs tag that ``VirtualMachineConfiguration``
    /// uses for the Rosetta share.  Kept here (and in the
    /// script below) so any future rename is a one-line
    /// search-and-replace.
    public static let tag = "rosetta"

    /// The mount point convention for the Rosetta share
    /// inside the guest.  `/mnt/rosetta` is the path used
    /// by most community docs and Docker's Rosetta
    /// integration, so sticking with it minimises surprise.
    public static let mountPoint = "/mnt/rosetta"

    /// Writes the setup script to a temporary file and
    /// returns its URL.  Used by the CLI's
    /// `--rosetta-setup` flag and the GUI's "Rosetta Setup"
    /// action — both of which then feed the script into the
    /// existing user-data / SSH-provisioning pipeline.
    public static func generate() throws -> URL {
        try ScriptFile.writeToCache(
            script: scriptContent(),
            fileName: "rosetta-setup.sh"
        )
    }

    /// Returns the shell script as a string, extracted for
    /// testability and for the "copy to clipboard" affordance
    /// in the GUI detail view.
    public static func scriptContent() -> String {
        """
        #!/bin/bash
        set -euo pipefail

        # Rosetta 2 setup for Linux guests under
        # Apple Virtualization.framework.
        # Generated by Spooktacular.
        #
        # Runs once, is idempotent, and follows Apple's
        # documented procedure from
        # https://developer.apple.com/documentation/virtualization/running-intel-binaries-in-linux-vms-with-rosetta

        TAG="\(tag)"
        MOUNT_POINT="\(mountPoint)"

        # --- 1. Install binfmt-support -----------------------------------
        # Provides `update-binfmts`, required for step 4.  Package
        # name is the same across apt/dnf/yum; Arch calls it
        # `binfmt-support` too.  Package-manager detection order
        # prefers apt (Debian/Ubuntu) → dnf (Fedora 22+) → yum
        # (RHEL/CentOS) → pacman (Arch).  If none match, the
        # script prints a hint and exits.
        if command -v update-binfmts >/dev/null 2>&1; then
            echo "update-binfmts already installed, skipping package install."
        elif command -v apt-get >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y binfmt-support
        elif command -v dnf >/dev/null 2>&1; then
            sudo dnf install -y binfmt-support || sudo dnf install -y systemd-binfmt
        elif command -v yum >/dev/null 2>&1; then
            sudo yum install -y binfmt-support
        elif command -v pacman >/dev/null 2>&1; then
            sudo pacman -Sy --noconfirm binfmt-support
        else
            echo "No supported package manager found." >&2
            echo "Install the 'binfmt-support' package manually, then rerun." >&2
            exit 1
        fi

        # --- 2. Create mount point ---------------------------------------
        sudo mkdir -p "$MOUNT_POINT"

        # --- 3. Mount virtio-fs share + persist via fstab -----------------
        # A plain `mount -t virtiofs` only survives until reboot.
        # Adding an `/etc/fstab` entry makes the mount happen
        # automatically on every boot so Rosetta stays live
        # without re-running this script.
        if ! mountpoint -q "$MOUNT_POINT"; then
            sudo mount -t virtiofs "$TAG" "$MOUNT_POINT"
        fi

        FSTAB_LINE="$TAG $MOUNT_POINT virtiofs ro,nofail 0 0"
        if ! grep -qsF "$FSTAB_LINE" /etc/fstab; then
            echo "$FSTAB_LINE" | sudo tee -a /etc/fstab >/dev/null
        fi

        # --- 4. Register Rosetta with binfmt_misc ------------------------
        # Apple's exact magic / mask values from the Virtualization
        # framework docs — the 20-byte x86_64 ELF header signature.
        # `--preserve yes` is required for macOS 14+; for macOS 13,
        # change to `--preserve no`.
        if update-binfmts --display rosetta >/dev/null 2>&1; then
            echo "Rosetta already registered with binfmt_misc, skipping."
        else
            sudo /usr/sbin/update-binfmts --install rosetta "$MOUNT_POINT/rosetta" \\
                --magic "\\x7fELF\\x02\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\x3e\\x00" \\
                --mask "\\xff\\xff\\xff\\xff\\xff\\xfe\\xfe\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff" \\
                --credentials yes \\
                --preserve yes \\
                --fix-binary yes
        fi

        echo
        echo "✓ Rosetta 2 is now active in this VM."
        echo "  Test: run an x86_64 binary, e.g."
        echo "    docker run --platform=linux/amd64 alpine uname -m"
        echo "  (should print x86_64)"
        """
    }
}
