import Foundation
import SpooktacularCore

/// Generates first-boot scripts for OpenClaw AI agent VMs.
///
/// When `spook create` is invoked with `--openclaw`, this template
/// generates the shell script that installs Node.js 24, installs
/// OpenClaw globally via npm, and configures the gateway daemon.
///
/// ## Execution context (why this looks the way it does)
///
/// The script runs **as root on first boot, before any user session
/// exists** — on macOS via the injected provisioner LaunchDaemon
/// (`DiskInjector`), on Linux via cloud-init's `runcmd`. That rules
/// out Homebrew (its installer refuses to run as root) and any
/// per-user idiom (`~/.zshrc`, user launchd sessions). Instead:
///
/// - **Node 24** comes from nodejs.org's official arm64 artifacts —
///   the `.pkg` via root-native `installer -pkg` on macOS, the
///   `linux-arm64.tar.xz` into `/usr/local` on Linux. The exact 24.x
///   version is resolved from `nodejs.org/dist/index.json` at script
///   runtime, never hardcoded.
/// - The script **waits for the provisioned account** (created by
///   macOS native provisioning / cloud-init during this same first
///   boot) before any per-user step, then drops privileges with
///   `sudo -u` — the same pattern ``GitHubRunnerTemplate`` uses
///   because `config.sh` refuses root.
/// - The **gateway** runs under the service manager (launchd
///   LaunchDaemon with a `UserName` key / systemd unit with `User=`),
///   not as a child of the provisioning script.
///
/// ## Security
///
/// API keys should be passed via a shared folder (`--share`), not
/// embedded in the script. The gateway daemon listens on port 18789
/// by default.
public enum OpenClawTemplate {

    /// Generates an OpenClaw setup script staged in the script cache.
    ///
    /// - Parameters:
    ///   - os: The guest operating system the script targets.
    ///   - username: The provisioned account the gateway runs as.
    /// - Returns: A file URL pointing to the generated script in a
    ///   temporary directory (owner-only permissions).
    /// - Throws: An error if the script cannot be written to disk.
    public static func generate(for os: GuestOS, username: String) throws -> URL {
        try ScriptFile.writeToCache(
            script: scriptContent(for: os, username: username),
            fileName: "openclaw-setup.sh"
        )
    }

    /// The complete first-boot script for the given guest OS.
    ///
    /// Extracted as a separate method for testability.
    ///
    /// - Parameters:
    ///   - os: The guest operating system the script targets.
    ///   - username: The provisioned account the gateway runs as.
    public static func scriptContent(for os: GuestOS, username: String) -> String {
        switch os {
        case .macOS: macOSScript(username: username)
        case .linux: linuxScript(username: username)
        }
    }

    // MARK: - macOS (root context: provisioner LaunchDaemon)

    private static func macOSScript(username: String) -> String {
        """
        #!/bin/bash
        set -euo pipefail

        # OpenClaw AI Agent Setup (macOS, runs as root on first boot)
        # Generated by Spooktacular
        OPENCLAW_USER="\(username)"

        # Wait for the provisioned account (created by macOS native
        # provisioning during this same first boot) to exist.
        for _ in $(seq 1 60); do
            id "$OPENCLAW_USER" >/dev/null 2>&1 && break
            sleep 2
        done

        # Node 24: newest 24.x from the official index (never
        # hardcoded), installed via the root-native pkg. User-session
        # package managers refuse to run as root, so none appear here.
        NODE_V=$(curl -fsSL https://nodejs.org/dist/index.json \\
            | grep -o '"v24[^"]*"' | head -1 | tr -d '"')
        curl -fsSL "https://nodejs.org/dist/${NODE_V}/node-${NODE_V}.pkg" -o /tmp/node.pkg
        installer -pkg /tmp/node.pkg -target /
        rm -f /tmp/node.pkg
        export PATH="/usr/local/bin:$PATH"

        # Install OpenClaw.
        npm install -g openclaw@latest

        # One-time onboarding as the provisioned user; non-fatal —
        # the LaunchDaemon below owns the gateway lifecycle.
        sudo -u "$OPENCLAW_USER" /usr/local/bin/openclaw onboard --install-daemon || true

        # Gateway runs as the provisioned user via launchd (UserName
        # key), not as root and not as a child of this script.
        cat > /Library/LaunchDaemons/com.spookylabs.openclaw.gateway.plist <<PLIST
        <?xml version="1.0" encoding="UTF-8"?>
        <plist version="1.0"><dict>
            <key>Label</key><string>com.spookylabs.openclaw.gateway</string>
            <key>UserName</key><string>\(username)</string>
            <key>ProgramArguments</key><array>
                <string>/usr/local/bin/openclaw</string><string>gateway</string>
            </array>
            <key>RunAtLoad</key><true/>
            <key>KeepAlive</key><true/>
        </dict></plist>
        PLIST
        launchctl load -w /Library/LaunchDaemons/com.spookylabs.openclaw.gateway.plist

        echo "OpenClaw installed; gateway running as ${OPENCLAW_USER} on port 18789"
        """
    }

    // MARK: - Linux (root context: cloud-init runcmd)

    private static func linuxScript(username: String) -> String {
        """
        #!/bin/bash
        set -euo pipefail

        # OpenClaw AI Agent Setup (Linux, runs as root via cloud-init)
        # Generated by Spooktacular
        OPENCLAW_USER="\(username)"

        # Wait for the provisioned account (created by cloud-init
        # during this same first boot) to exist.
        for _ in $(seq 1 60); do
            id "$OPENCLAW_USER" >/dev/null 2>&1 && break
            sleep 2
        done

        # Node 24: newest 24.x from the official index (never
        # hardcoded), official arm64 tarball into /usr/local.
        NODE_V=$(curl -fsSL https://nodejs.org/dist/index.json \\
            | grep -o '"v24[^"]*"' | head -1 | tr -d '"')
        curl -fsSL "https://nodejs.org/dist/${NODE_V}/node-${NODE_V}-linux-arm64.tar.xz" -o /tmp/node.tar.xz
        tar -xJf /tmp/node.tar.xz -C /usr/local --strip-components=1
        rm -f /tmp/node.tar.xz
        export PATH="/usr/local/bin:$PATH"

        # Install OpenClaw.
        npm install -g openclaw@latest

        # One-time onboarding as the provisioned user; non-fatal —
        # the systemd unit below owns the gateway lifecycle.
        sudo -u "$OPENCLAW_USER" /usr/local/bin/openclaw onboard --install-daemon || true

        # Gateway runs as the provisioned user under systemd.
        cat > /etc/systemd/system/openclaw-gateway.service <<UNIT
        [Unit]
        Description=OpenClaw gateway
        After=network-online.target
        Wants=network-online.target

        [Service]
        User=\(username)
        ExecStart=/usr/local/bin/openclaw gateway
        Restart=always

        [Install]
        WantedBy=multi-user.target
        UNIT
        systemctl daemon-reload
        systemctl enable --now openclaw-gateway.service

        echo "OpenClaw installed; gateway running as ${OPENCLAW_USER} on port 18789"
        """
    }
}
