import Foundation
import SpooktacularCore

/// Generates first-boot scripts for OpenClaw AI agent VMs.
///
/// When `spook create` is invoked with `--openclaw`, this template
/// generates the shell script that installs Node.js 24, installs
/// OpenClaw globally via npm, and configures the gateway daemon.
///
/// ## Execution context (why this looks the way it does)
///
/// The script runs **as root on first boot, before any user session
/// exists** — on macOS via the injected provisioner LaunchDaemon
/// (`DiskInjector`), on Linux via cloud-init's `runcmd`. That rules
/// out Homebrew (its installer refuses to run as root) and any
/// per-user idiom (`~/.zshrc`, user launchd sessions). Instead:
///
/// - **Node 24** comes from nodejs.org's official arm64 artifacts —
///   the `.pkg` via root-native `installer -pkg` on macOS, the
///   `linux-arm64.tar.xz` into `/usr/local` on Linux. The exact 24.x
///   version is resolved from `nodejs.org/dist/index.json` at script
///   runtime, never hardcoded.
/// - The script **waits for the provisioned account** (created by
///   macOS native provisioning / cloud-init during this same first
///   boot) before any per-user step, then drops privileges with
///   `sudo -u` — the same pattern ``GitHubRunnerTemplate`` uses
///   because `config.sh` refuses root.
/// - The **gateway** is installed by OpenClaw's own
///   `onboard --install-daemon` as a per-user launchd/systemd service
///   (the documented mechanism), not by a hand-rolled unit. On Linux
///   the script enables user lingering so that service can run
///   headless. Fully activating the gateway (port 18789) needs channel
///   credentials, supplied out-of-band via `--share`.
///
/// ## Security
///
/// API keys should be passed via a shared folder (`--share`), not
/// embedded in the script. The gateway daemon listens on port 18789
/// by default.
public enum OpenClawTemplate {

    /// Generates an OpenClaw setup script staged in the script cache.
    ///
    /// - Parameters:
    ///   - os: The guest operating system the script targets.
    ///   - username: The provisioned account the gateway runs as.
    /// - Returns: A file URL pointing to the generated script in a
    ///   temporary directory (owner-only permissions).
    /// - Throws: An error if the script cannot be written to disk.
    public static func generate(for os: GuestOS, username: String) throws -> URL {
        try ScriptFile.writeToCache(
            script: scriptContent(for: os, username: username),
            fileName: "openclaw-setup.sh"
        )
    }

    /// The complete first-boot script for the given guest OS.
    ///
    /// Extracted as a separate method for testability.
    ///
    /// - Parameters:
    ///   - os: The guest operating system the script targets.
    ///   - username: The provisioned account the gateway runs as.
    public static func scriptContent(for os: GuestOS, username: String) -> String {
        switch os {
        case .macOS: macOSScript(username: username)
        case .linux: linuxScript(username: username)
        }
    }

    // MARK: - macOS (root context: provisioner LaunchDaemon)

    private static func macOSScript(username: String) -> String {
        """
        #!/bin/bash
        set -euo pipefail

        # OpenClaw AI Agent Setup (macOS, runs as root on first boot)
        # Generated by Spooktacular
        OPENCLAW_USER="\(username)"

        # Wait for the provisioned account (created by macOS native
        # provisioning during this same first boot) to exist.
        for _ in $(seq 1 60); do
            id "$OPENCLAW_USER" >/dev/null 2>&1 && break
            sleep 2
        done

        # Node 24: newest 24.x from the official index (never
        # hardcoded), installed via the root-native pkg. User-session
        # package managers refuse to run as root, so none appear here.
        NODE_V=$(curl -fsSL https://nodejs.org/dist/index.json \\
            | grep -o '"v24[^"]*"' | head -1 | tr -d '"')
        curl -fsSL "https://nodejs.org/dist/${NODE_V}/node-${NODE_V}.pkg" -o /tmp/node.pkg
        installer -pkg /tmp/node.pkg -target /
        rm -f /tmp/node.pkg
        export PATH="/usr/local/bin:$PATH"

        # Install OpenClaw.
        npm install -g openclaw@latest

        # OpenClaw's own onboarding installs the gateway as a per-user
        # launchd service (`--install-daemon`, per its docs — it's the
        # documented way to keep the gateway running). Run it as the
        # provisioned user; the service activates when that user has a
        # session (e.g. connecting via Screen Sharing on a
        # remote-desktop VM). Non-interactive here (`</dev/null`) —
        # channel credentials, supplied via `--share`, are what fully
        # bring the gateway up on port 18789.
        sudo -u "$OPENCLAW_USER" /usr/local/bin/openclaw onboard --install-daemon </dev/null || true

        echo "OpenClaw installed for ${OPENCLAW_USER}; run 'openclaw onboard' with credentials to activate the gateway (port 18789)"
        """
    }

    // MARK: - Linux (root context: cloud-init runcmd)

    private static func linuxScript(username: String) -> String {
        """
        #!/bin/bash
        set -euo pipefail

        # OpenClaw AI Agent Setup (Linux, runs as root via cloud-init)
        # Generated by Spooktacular
        OPENCLAW_USER="\(username)"

        # Wait for the provisioned account (created by cloud-init
        # during this same first boot) to exist.
        for _ in $(seq 1 60); do
            id "$OPENCLAW_USER" >/dev/null 2>&1 && break
            sleep 2
        done

        # Node 24: newest 24.x from the official index (never
        # hardcoded), official arm64 tarball into /usr/local.
        NODE_V=$(curl -fsSL https://nodejs.org/dist/index.json \\
            | grep -o '"v24[^"]*"' | head -1 | tr -d '"')
        curl -fsSL "https://nodejs.org/dist/${NODE_V}/node-${NODE_V}-linux-arm64.tar.xz" -o /tmp/node.tar.xz
        tar -xJf /tmp/node.tar.xz -C /usr/local --strip-components=1
        rm -f /tmp/node.tar.xz
        export PATH="/usr/local/bin:$PATH"

        # Install OpenClaw.
        npm install -g openclaw@latest

        # Enable lingering so the provisioned user's systemd services
        # run at boot without an interactive login (headless cloud VM).
        loginctl enable-linger "$OPENCLAW_USER" || true

        # OpenClaw's onboarding installs the gateway as a per-user
        # systemd service (`--install-daemon`, per its docs — the
        # documented way to keep it running). Non-interactive here
        # (`</dev/null`); channel credentials, supplied via `--share`,
        # are what fully bring the gateway up on port 18789.
        sudo -u "$OPENCLAW_USER" \\
            XDG_RUNTIME_DIR="/run/user/$(id -u "$OPENCLAW_USER")" \\
            /usr/local/bin/openclaw onboard --install-daemon </dev/null || true

        echo "OpenClaw installed for ${OPENCLAW_USER}; run 'openclaw onboard' with credentials to activate the gateway (port 18789)"
        """
    }
}
